# Generated by Django 5.2.5 on 2026-01-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Price',
            new_name='productID',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Qty',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
