# Generated by Django 5.2.5 on 2026-01-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='productID',
            new_name='product',
        ),
    ]
