# Generated by Django 5.2.5 on 2026-01-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_productid_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CANCELLED', 'Cancelled'), ('CREATED', 'Created'), ('SHIPPED', 'Shippped'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=20),
        ),
    ]
