# Generated by Django 5.2.5 on 2026-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CANCELLED', 'Cancelled'), ('CREATED', 'Created'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=20),
        ),
    ]
