# Generated by Django 5.2.5 on 2026-01-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_stock',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
