# Generated by Django 5.2.5 on 2026-01-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_updated_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_stock',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
