# Generated by Django 5.2.5 on 2026-01-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_updated_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated_stock',
            new_name='updated_stock_at',
        ),
    ]
